#!/bin/bash

# Define command-line arguments
RESOURCE_TYPE=$1

# Retrieve resource usage statistics from Kubernetes

if [[ $RESOURCE_TYPE = "pod" ]]
then
    flag=-A
fi

sudo kubectl top $RESOURCE_TYPE $flag | tail -n +2 | while read line

do
  # Extract CPU and memory usage from the output
  NAMESPACE=$(echo $line | awk '{print $1}')
  NAME=$(echo $line | awk '{print $2}')
  CPU=$(echo $line | awk '{print $3}')
  MEMORY=$(echo $line | awk '{print $4}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done
